export const DOCUMENT_MAPPINGS = {
    cmnd: {
        anh_chan_dung: 'Ảnh chân dung',
        id: 'Số',
        loai_vb: 'Loại văn bản',
        ngay_sinh: 'Sinh ngày',
        noi_thuong_tru: 'Nơi ĐKHK thường trú',
        que_quan: 'Nguyên quán',
        ten_chu_the: 'Tên chủ thẻ',
        gioi_tinh: 'Giới tính',
        dan_toc: 'Dân tộc',
        dac_diem_nhan_dang: 'Đặc điểm nhận dạng',
        noi_cap: 'Nơi cấp',
        thong_tin_ngay_cap: 'Thông tin ngày cấp',
        ton_giao: 'Không',
        cmnd_mat_truoc: 'CMND mặt trước',
        cmnd_mat_sau: 'CMND mặt sau',
    },

    gplx: {
        hang: 'Hạng/Class',
        loai_vb: 'Loại văn bản',
        ngay_cap: 'Ngày cấp',
        nam: 'Năm/Year',
        thang: 'Tháng/Month',
        ngay: 'Ngày/Date',
        ngay_het_hieu_luc: 'Ngày hết hiệu lực/Expires',
        ngay_sinh: 'Ngày sinh/Date of Birth',
        noi_cu_tru: 'Nơi cư trú/Address',
        quoc_tich: 'Quốc tịch/Nationality',
        so: 'Số/No',
        ten_nguoi: 'Họ tên/Fullname',
        cac_loai_xe_co_gioi_duoc_dieu_khien: 'Các loại xe cơ giới được điều khiển',
        ngay_trung_tuyen: 'Ngày trúng tuyển',
        giay_phep_lai_xe_mat_truoc: 'Giấy phép lái xe mặt trước',
        giay_phep_lai_xe_mat_sau: 'Giấy phép lái xe mặt sau',
    },

    invoice: {
        dia_chi_benh_nhan: 'Địa chỉ',
        don_gia: 'Đơn giá',
        don_vi: 'Đơn vị',
        ky_hieu_hoa_don: 'Ký hiệu hóa đơn',
        loai_vb: 'Loại văn bản',
        mau_so_hoa_don: 'Mẫu số hóa đơn',
        ngay: 'Ngày',
        noi_dung: 'Nội dung',
        so_luong: 'Số lượng',
        ten_benh_nhan: 'Tên người/đơn vị mua hàng',
        ten_dich_vu: 'Tên dịch vụ',
        thanh_tien: 'Thành tiền',
        tong_tien_bang_so: 'Tổng tiền bằng số',
        thong_tin_thoi_gian: 'Thông tin thời gian',
    },

    gthc: {
        chuc_vu: 'Chức vụ',
        co_quan_ban_hanh: 'Cơ quan ban hành',
        do_khan: 'Độ khẩn',
        doc_type: 'Loại văn bản',
        lang: 'Ngôn ngữ',
        ngay_ban_hanh: 'Ngày ban hành',
        ngay_den: 'Ngày đến',
        nam: 'Năm',
        thang: 'Tháng',
        ngay: 'Ngày',
        nguoi_ky: 'Người ký',
        noi_nhan_ben_ngoai: 'Nơi nhận bên ngoài',
        noi_nhan_ben_trong: 'Nơi nhận bên trong',
        so_den: 'Số đến',
        so_ky_hieu: 'Số ký hiệu',
        so_trang: 'Số trang',
        ten_van_ban: 'Tên văn bản',
        trich_yeu: 'Trích yếu',
        vi: 'Tiếng Việt',
    },
};
